### ISSUE TITLE
Issue for Chapters with Spoiler Names

### ISSUE THREAD

**Issue by MrHaCkEr** [MakeYourLifeEasier/Wuxiaworld-2-eBook#14]
There seems to be a problem with hidden chapter names i.e. chapter 74: A Will Eternal.

Seems to be a parsing issue.

**Comment by Ryuichiro** [comment]
I would take a look at it, which Novel is the example?

**Comment by MrHaCkEr** [comment]
Great! I'll just copy the important content from the E-Mail I received regarding this bug. That's all I know about as I did not look into it atm:

> Hey,
I noticed that the program seems to break when it downloads a chapter with a spoiler name. For example, chapter 74 of A Will Eternal (http://www.wuxiaworld.com/awe-index/awe-chapter-74/). 
After looking around at the code, I noticed that when the the raw data is parsed in getify.py on soup = BeautifulSoup(raw, 'html.parser’) it isn’t parsed super accurately. This leads to issues with your other code because the tags don’t match as well as the chapters without spoilers, so it misses all of the actual content of the chapter.

**Comment by Ryuichiro** [comment]
The Question is what do we want to happen when it encounters a spoiler title?
Only show the chapter number or show the full spoiler?

**Comment by MrHaCkEr** [comment]
How about chapter number + „Title hidden due to potential spoilers“ or something like that and at the end of the chapter the name in bold?

**Comment by Ryuichiro** [comment]
Ok, I think the problem is inside getify.clean() not BeautifulSoup so it should be possible to catch this special case and work around it.

**Comment by Ryuichiro** [comment]
Sadly the problem is inside BeautifulSoup.
The .find() command only selects until it finds the first end tag so in this case it tries to select a div but because there is another div inside it, it stops when it encounter the </div> and ends up with this:
```                                <div itemprop="articleBody">
                                    <p>
                                        <a title="Chapter 73" href="http://www.wuxiaworld.com/awe-index/awe-chapter-73/">Previous Chapter</a>
                                        <span style="float: right">
                                            <a title="Chapter 75" href="http://www.wuxiaworld.com/awe-index/awe-chapter-75/">Next Chapter</a>
                                        </span>
                                    </p>
                                    <hr />
                                    <p>
                                        <strong>
                                            <span class="collapseomatic " id="id7676" tabindex="" title="Chapter 74 (Click to show "
                                                spoiler " title)">Chapter 74 (Click to show "spoiler" title)</span>
                                            <div id="target-id7676" class="collapseomatic_content ">
                                                <p> Chapter 74: So, It Was Bai Xiaochun!</p>
                                                <p>
                                        </strong>
                                        <br />
                                        </div>```
I'm searching through the BeautifulSoup API to find a workaround, but no luck so far.

**Comment by MrHaCkEr** [comment]
Currently not at home so I can't look through the API , but you probably want to check for child elements of the first div, and if it contains one with the specific class mentioned, clean differently. 
Could also be nonsense what I'm writing,  if you can't figure it out, I'll take a look at it sometime this weekend.

**Comment by MrHaCkEr** [comment]
Fixed it.
