### ISSUE TITLE
New Site & New Links

### ISSUE THREAD

**Issue by UsamaWaheed** [MakeYourLifeEasier/Wuxiaworld-2-eBook#15]
Hi,

I know you worked really hard on this. Wuxia updated their sites and links. Any chance of getting a revised version of this for the new website?

Thanks in advance.

**Comment by MrHaCkEr** [comment]
Yes, I’ll make it compatible with the new link structure. Hopefully within 24 hours.

**Comment by UsamaWaheed** [comment]
Thanks. Will wait for the update. Btw are you gonna make any new changes to software like status bar and/or other customizable feature?

**Comment by MrHaCkEr** [comment]
Updated everything for the new site.
I'm planning to add a status bar with the next big update, in fact the code is already inside the program it only needs to be activated.
But I currently don't have the time or motivation to work on this program so it's put on hold atm. 
Customization features are not planned expect the feature to use your own .css file for formatting.
