### ISSUE TITLE
Issue with New Code

### ISSUE THREAD

**Issue by UsamaWaheed** [MakeYourLifeEasier/Wuxiaworld-2-eBook#16]
Hi,

I get error with new code as soon as I run it.

On the CMD screenshot below, I have split it into two errors:

1. When we run the program as is.
2. When we comment out the if chapter_title line then we get the second error.

Please find the screenshot as below:

![mar-11 -000- 11 29 10 am](https://user-images.githubusercontent.com/35238840/37250500-4b7bdea8-2520-11e8-89f2-657b1288d60f.png)

**Comment by MrHaCkEr** [comment]
Thanks for pointing it out! I commited the wrong files yesterday, should be working now.

I did not get the second error in my testing, if it does appear in the new version just comment under this issue with the specific chapter number and book name so I can take a look.

**Comment by UsamaWaheed** [comment]
Thanks, the first error is gone. However, the second one persists. 
In order to reproduce it, try the following:

**> Novel: Martial World
> Start: 1476
> End: 1499**
Thanks again for the prompt responses

**Comment by MrHaCkEr** [comment]
I see. The way I wrote the part to get the chapter title doesn't seem to work out as expected. Only tested the code on two novels. I'll write a fix for it in the next couple of days.

For now just change line 39 in getify.py to:
`chapter_title = soup.find("span").text`
or to:
`chapter_title = soup.find("strong").extract().text`
This will make it work for matrial world but will break code for some other novels.

I can't test it atm but if both of those fixes don't work just use:
`chapter_title = "Some random string"`
this will break the table of contents but will fix this bug across all novels.

**Comment by MrHaCkEr** [comment]
Actually found some time. New update should fix the problem. Didn't check but it should work now for all novels.
