### ISSUE TITLE
Issue with Desolate Era

### ISSUE THREAD

**Issue by UsamaWaheed** [MakeYourLifeEasier/Wuxiaworld-2-eBook#17]
Hi Buddy,

Sorry for reporting so many issues. The previous issues were resolved and the best part is, it's working faster now.

However, just tried publishing Desolate Era, it gave an error for which screenshot is attached below:

Book: 42
Chapters: 1 - 21

![mar-12 -002- 12 55 27 pm](https://user-images.githubusercontent.com/35238840/37271479-e1986936-25f4-11e8-9d50-9b0aa57fb385.png)

**Comment by MrHaCkEr** [comment]
No problem, I can’t check every novel for issues. Will fix it when I’m back from work.

**Comment by MrHaCkEr** [comment]
Fixed.
