### ISSUE TITLE
Unable to download Desolate Era Book

### ISSUE THREAD

**Issue by West-R** [MakeYourLifeEasier/Wuxiaworld-2-eBook#18]
It's been fine downloading the series up until this point, I haven't checked any books beyond this one.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__in
it__.py", line 1699, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 70, in button_press
    getify.clean(str(s_chapter) + ".xhtml", raw_info[2] + str(s_chapter), name)
  File "C:\Users\User\Desktop\wuxiadl\getify.py", line 51, in clean
    chapter_title = chapter_title[chapter_title.index(",") + 1:]
ValueError: substring not found`

![wuxiadl-de-issues](https://user-images.githubusercontent.com/7952233/40262227-d9395534-5ad3-11e8-84d4-43ad336051d5.png)
![de_issue](https://user-images.githubusercontent.com/7952233/40262237-e287d106-5ad3-11e8-96db-226b762b8ce5.png)

I'd also like to ask if it would be too difficult to add an option to download the entire novel in one go, rather than book-by-book.

Thanks. This script has been very helpful.

**Comment by MrHaCkEr** [comment]
Thanks for reporting the error, seems to come from an earlier attempt on reducing the chapter title length of desolate era books. I will take a look into it.

As for the suggested feature, the way that the script is implemented makes it impossible without rewriting a significant portion of the script.
