### ISSUE TITLE
About

### ISSUE THREAD

**Issue by Kogam22** [MakeYourLifeEasier/Wuxiaworld-2-eBook#21]
Is this a modified version of Qidan's Python Script for downloading chapters into .epub format ?
Or ... maybe not.

**Comment by MrHaCkEr** [comment]
Don't know which script you're referring to? Would you mind linking it?

This was written from scratch as a project to learn python.

**Comment by Kogam22** [comment]
@MrHaCkEr
> Don't know which script you're referring to. Would you mind linking it?

> This was written from scratch as a project to learn python.

That's wonderful. I modified one for some hands on experience as I am not that good ^_^

**Comment by MrHaCkEr** [comment]
>  I modified one for some hands on experience as I am not that good ^_^

It's all about learning. I'm not that good either but I gained quite a bit of knowledge writing this script. If I'd rewrote the script today, I bet it would turn out a lot better.

If your interested behind the concept, I've written a tutorial behind the basic principles of the script:
[Creating .epub files in Python](https://steemit.com/utopian-io/@bloodviolet/creating-epub-files-in-python-part-4-creating-the-epub-file)
You can find the links to the previous parts at the bottom of the post.
