### ISSUE TITLE
Add a way to batch process multiple Books

### ISSUE THREAD

**Issue by leonard84** [MakeYourLifeEasier/Wuxiaworld-2-eBook#25]
* This could be done via a command line interface.
* Or add a list of break chapters, e.g. Start 1 End 1200 BreakAfter 284,391,628,786,1043

**Comment by MichaelGuardian** [comment]
Thanks for opening up an issue!

Did not add batch processing for books to keep content aggregation in check.
Noted chapter breaks for eventual future release.
