### ISSUE TITLE
Talisman Emperor

### ISSUE THREAD

**Issue by moexius** [MakeYourLifeEasier/Wuxiaworld-2-eBook#29]
Hi there,

There are some issues with the app and novel Talisman Emperor. 

1. The URL at later chapters changed from https://www.wuxiaworld.com/novel/talisman-emperor/te-book to https://www.wuxiaworld.com/novel/talisman-emperor/te-
I was able to fix this by editing novels.db myself
2. The app needs to rectify how it identifies TE as to not expect a book number
I was able to bypass this, **only for TE**, by modified wuxiaworld2ebook.py_line 46 from **link = raw_info[1] + str(booknr) + "-chapter-"** to **link = raw_info[1] + "chapter-"**
3. There is an announcement on top of the each chapter right now. The code extracting the SOUP is not handling this very well and it does not add the actual soup of the chapter, but a partial of the announcement
4. There might be more things wrong, but I just focus on TE as this is the current novel I am reading at the moment

It would be great if you could add some fixes whenever possible.

Thanks in advance.

**Comment by moexius** [comment]
Ok. So I found a workaround. I am really not familiar with python, getify and beautifulSoup. That being said, after some tries and fails, I more or less learn some of the logic behind selecting the proper soup. 

The logic I got to understand probably is wrong but someone it does what w2ebook was meant to do, at least for TALISMAN EMPEROR.

At line 46 from getify, the soup is specified to **soup = soup.find(class_="fr-view")**. I reckon that BeautifulSoup is parsing this wrong due to the announcement as it share similar class names:
Announcement has a class called CLEARFIX
body of the chapter has a class called CAPTION CLEARFIX

I suppose CAPTION CLEARFIX is not matching exactly therefore taking the announcement as it's first. Again, this logic might be wrong but this logic allowed to get to a workaround that works for me.

So the change I did is, 

    **soup = soup.find(class_="fr-view")**
to
    **soup = soup.find(class_="panel panel-default")**
    **soup = soup.find(class_="fr-view")**

Most likely, you can properly fix this. but for now, I get to download the freaking chapters.

**Comment by MrHaCkEr** [comment]
Thanks for pointing this issue out.

I'll release a hotfix after work.

If I recall correctly the caption clearfix class is most commonly used to hide chapter spoilers, so it was used to detect that kind of stuff.

**Comment by MichaelGuardian** [comment]
Fixed thanks to the courtesy of @ashussen a couple of commits ago.
