### ISSUE TITLE
Downloads announcement instead of chapters

### ISSUE THREAD

**Issue by Poofey** [MakeYourLifeEasier/Wuxiaworld-2-eBook#31]
Wuxiaworld has an announcement on top of the novels right now and the script takes the announcement as the chapter and downloads that instead.
![capture](https://user-images.githubusercontent.com/8733219/48319620-e4379a00-e5c4-11e8-9789-73b8ede6c244.JPG)

**Comment by MrHaCkEr** [comment]
Thanks for reporting this issue!

Have quite a bit of stuff to do so I didn't manage to fix it up to this point. Hopefully I'll come around fixing in the next couple of days.

**Comment by MrHaCkEr** [comment]
Fixed thanks to the courtesy of @ashussen.
