### ISSUE TITLE
Certificate error 

### ISSUE THREAD

**Issue by wegner94** [MakeYourLifeEasier/Wuxiaworld-2-eBook#41]
Error every time when I try to download:
'URL: http://www.wuxiaworld.com/novel/talisman-emperor/te-book-1-chapter-1, URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)' 

It suddenly appeared; I have downloaded several light novels before without any problems. I tried one that worked for me before (Martial World) but it didn't work either.

**Comment by MichaelGuardian** [comment]
Could you provide your operating system and python version?

Also check out [this link](https://github.com/MakeYourLifeEasier/Wuxiaworld-2-eBook/issues/35) with a fix for this issue.

**Comment by wegner94** [comment]
Windows 7
Python 3.7.1

**Comment by MichaelGuardian** [comment]
Well no idea why this is happening but considering the use-case of this script, it's probably safe to disable the ssl verification. Will remove it in a couple of hours if I don't forget it.

**Comment by wegner94** [comment]
Thanks

**Comment by MichaelGuardian** [comment]
It seems I did forget it. If you still have the problem feel free to try out [this side project](https://novel-ebook.com) of mine that should work more consistently across operating systems.
