### ISSUE TITLE
Unable To Download Ebooks

### ISSUE THREAD

**Issue by RuthlessRuler** [MakeYourLifeEasier/Wuxiaworld-2-eBook#42]
I'm Getting Error, IndexError: list index out of range.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 82, in button_press
    getify.clean(str(s_chapter) + ".xhtml", _get_xhtml_path(raw_info, s_chapter), name)
  File "C:\Users\User\Downloads\Wuxiaworld-2-eBook-master\getify.py", line 44, in clean
    if chapter_title.attrs["class"][0] == "text-spoiler":
IndexError: list index out of range`

**Comment by MichaelGuardian** [comment]
Which novel where you downloading? What was the chapter range? 

Could you also specify your operating system and Python version?

**Comment by rekbitt** [comment]
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\**\AppData\Local\Programs\Python\Python37-32\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "wuxiaworld2ebook.py", line 82, in button_press
    getify.clean(str(s_chapter) + ".xhtml", _get_xhtml_path(raw_info, s_chapter), name)
  File "C:\[Epubs]\Wuxiaworld-2-eBook-master\getify.py", line 44, in clean
    if chapter_title.attrs["class"][0] == "text-spoiler":
IndexError: list index out of range`

![image](https://user-images.githubusercontent.com/29830383/54044228-677e9a80-4209-11e9-8d18-3ca1a5127ccd.png)
![image](https://user-images.githubusercontent.com/29830383/54044438-e96ec380-4209-11e9-8566-aedb443654f7.png)


Have the same problem. am I doing wrong something wrong in generating the epubs?

**Comment by MichaelGuardian** [comment]
I just updated the code. @rmumu Could you verify if this fixes the issue? I couldn't replicate the bug on my system.

**Comment by RuthlessRuler** [comment]
It Was Battle Through The Heavens.
I tried downloading chapter 400 -600

**Comment by RuthlessRuler** [comment]
Wu Dong Qian Kun Chapter 577b and 578b doesnt download.

**Comment by MichaelGuardian** [comment]
It works for me. What browser are you using?

**Comment by RuthlessRuler** [comment]
What? I'm using the latest version of the script.
IDK why browser matters, it's ff

**Comment by MichaelGuardian** [comment]
Oh, I thought this was a different project, my bad.
The problem is that the urls dont follow the standart in these chapters. Since the script just adds the chapter number at the end of a url it doesn't pick up urls that have more then just a number at the end (eg. 577-1).

This won't be fixed since a rewrite would be necessary. [The javascript port](https://novel-ebook.com/) of this project does account for it but it's still in alpha stage.
